# Generated by Django 2.2.5 on 2019-10-11 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0009_auto_20191011_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='follows',
            new_name='Follow',
        ),
    ]
