# Generated by Django 2.2.5 on 2019-10-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_auto_20191011_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/'),
        ),
    ]
