# Generated by Django 2.2.5 on 2019-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_auto_20191011_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile/     default.jpg', upload_to='profile/'),
        ),
    ]
